import { GalleryImage, ReviewItem, ServiceItem } from './types';

export const SALON_INFO = {
  name: "Gentleman Coif",
  type: "Salon de coiffure homme & Barbershop d'exception",
  tagline: "L'excellence de la coupe, l'art du style",
  rating: 5.0,
  reviewCount: 77,
  addressCode: "V5VJ+MCJ",
  city: "Tunis",
  fullAddress: "V5VJ+MCJ, Tunis, Tunisie",
  phoneDisplay: "52 961 481",
  phoneRaw: "52961481",
  phoneInternational: "+21652961481",
  status: "Ouvert · Ferme à 23:00",
  closingTime: "23:00",
  hoursText: "Tous les jours de 10:00 à 23:00",
  googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=V5VJ%2BMCJ%2C+Tunis",
  googleDirectionsUrl: "https://www.google.com/maps/dir/?api=1&destination=V5VJ%2BMCJ%2C+Tunis",
  embedMapUrl: "https://maps.google.com/maps?q=V5VJ%2BMCJ%2C%20Tunis&t=&z=15&ie=UTF8&iwloc=&output=embed",
  whatsappUrl: "https://wa.me/21652961481?text=Bonjour%20Gentleman%20Coif,%20je%20souhaite%20prendre%20rendez-vous.",
};

export const SERVICES: ServiceItem[] = [
  {
    id: "coupe-signature",
    name: "Coupe Homme Signature",
    tagline: "Conseil visagiste personnalisé",
    price: "25 DT",
    duration: "30 min",
    description: "Shampoing traitant, diagnostic morphologique, coupe aux ciseaux et tondeuse de précision, coiffage aux cires premium.",
    iconName: "Scissors",
    popular: true,
  },
  {
    id: "degrade-americain",
    name: "Dégradé Américain (Fade)",
    tagline: "Précision chirurgicale",
    price: "25 DT",
    duration: "35 min",
    description: "Dégradé à blanc progressif (Low, Mid ou High Fade), contours nets rasoir et finitions impeccables.",
    iconName: "Sparkles",
    popular: true,
  },
  {
    id: "taille-barbe",
    name: "Taille & Sculpture de Barbe",
    tagline: "Soin et tracé haute précision",
    price: "18 DT",
    duration: "25 min",
    description: "Restructuration de la barbe, traçage des contours au rasoir, application d'huile nourrissante et baume satiné.",
    iconName: "Flame",
  },
  {
    id: "rasage-traditionnel",
    name: "Rasage Traditionnel & Serviette Chaude",
    tagline: "Le rituel barbier à l'ancienne",
    price: "22 DT",
    duration: "30 min",
    description: "Préparation à l'huile de ricin, double serviette chaude aux huiles essentielles, rasage au coupe-chou et pierre d'alun.",
    iconName: "Crown",
  },
  {
    id: "coupe-enfant",
    name: "Coupe Enfant (Dès 2 ans)",
    tagline: "Douceur, bienveillance & patience",
    price: "20 DT",
    duration: "25 min",
    description: "Une expérience chaleureuse et apaisante pour les tout-petits et jeunes garçons. Coiffeur attentionné et résultat soigné.",
    iconName: "Smile",
    popular: true,
  },
  {
    id: "soin-visage",
    name: "Soin Visage Purifiant & Black Mask",
    tagline: "Éclat et pureté immédiats",
    price: "20 DT",
    duration: "20 min",
    description: "Vapeur ozonée, gommage exfoliant doux, masque charbon noir désincrustant et crème hydratante matifiante.",
    iconName: "Droplets",
  },
  {
    id: "pack-gentleman",
    name: "Pack VIP Gentleman",
    tagline: "L'expérience complète de luxe",
    price: "50 DT",
    duration: "65 min",
    description: "Coupe signature complète + Taille de barbe au coupe-chou avec serviette chaude + Soin visage express + Boisson offerte.",
    iconName: "Gem",
    popular: true,
  },
  {
    id: "couleur-camouflage",
    name: "Camouflage Poils Blancs & Soin",
    tagline: "Résultat naturel et discret",
    price: "25 DT",
    duration: "25 min",
    description: "Atténuation subtile des cheveux ou barbes poivre et sel sans effet casque, estompage progressif et élégant.",
    iconName: "Wand2",
  },
];

export const REVIEWS: ReviewItem[] = [
  {
    id: "rev-1",
    author: "Ameni Berkaoui",
    date: "Il y a 2 semaines",
    rating: 5.0,
    text: "Très belle expérience pour la première coupe de ma fille de 2 ans. Le coiffeur était très gentil, doux et professionnel. La coupe est magnifique, je recommande",
    highlight: "Coiffeur très doux et professionnel avec les enfants",
  },
  {
    id: "rev-2",
    author: "Farouk Bentaleb",
    date: "Il y a 1 mois",
    rating: 5.0,
    text: "Very friendly staff, very good service, a good haircut and professional skills! Highly recommended.",
    highlight: "Professional skills and top service",
  },
  {
    id: "rev-3",
    author: "Marwen Garaali",
    date: "Il y a 3 semaines",
    rating: 5.0,
    text: "Très satisfait de mon passage. Coiffeur professionnel, à l'écoute et résultat au top. Je recommande sans hésitation.",
    highlight: "À l'écoute et résultat au top",
  },
];

export const GALLERY_IMAGES: GalleryImage[] = [
  {
    id: "gal-1",
    title: "Dégradé Américain & Coiffage Structuré",
    category: "coupes",
    imageUrl: "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?q=80&w=1200&auto=format&fit=crop",
    alt: "Coupe homme dégradé américain haute précision chez Gentleman Coif",
  },
  {
    id: "gal-2",
    title: "Taille de Barbe & Traçage Rasoir",
    category: "barbe",
    imageUrl: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?q=80&w=1200&auto=format&fit=crop",
    alt: "Sculpture et finition de barbe au rasoir traditionnel",
  },
  {
    id: "gal-3",
    title: "Le Salon & Fauteuils Vintage en Cuir",
    category: "ambiance",
    imageUrl: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?q=80&w=1200&auto=format&fit=crop",
    alt: "Ambiance vintage moderne et fauteuils de barbier en cuir",
  },
  {
    id: "gal-4",
    title: "Coupe Ciseaux & Texture Moderne",
    category: "coupes",
    imageUrl: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?q=80&w=1200&auto=format&fit=crop",
    alt: "Finition aux ciseaux sur coupe homme élégante",
  },
  {
    id: "gal-5",
    title: "Rituel Rasage Traditionnel & Coupe-Chou",
    category: "barbe",
    imageUrl: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?q=80&w=1200&auto=format&fit=crop",
    alt: "Rasage traditionnel avec crème mousseuse et coupe-chou",
  },
  {
    id: "gal-6",
    title: "Outils de Précision & Cires Premium",
    category: "ambiance",
    imageUrl: "https://images.unsplash.com/photo-1512690459411-b9245aed614b?q=80&w=1200&auto=format&fit=crop",
    alt: "Outils de barbier haut de gamme en acier chromé et or",
  },
];
